{% set name = "doped" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SMTG-UCL/doped/archive/{{ version }}.tar.gz
  sha256: dadbe46547b52361c84322ba9913cab35a37bb5fd2b3d1a619211ffc577b76f9


# PyPI (no test files...)
#  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
#  sha256: a1eca51ccdc1fdc9e71e39d1f864c4cf472c7452fa86c717ab192688afa9a933

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<3.11
  run:
    - python >=3.7,<3.11
    - ase
    - tabulate
    - matplotlib-base
    - numpy >=1.21.0
    - pymatgen <2022.8.23

test:
  imports:
    - doped

about:
  home: https://github.com/SMTG-UCL/doped
  license: MIT
  license_file: LICENSE
  summary: Python package to setup, process and analyse solid-state defect calculations with VASP
  description: |
    DOPED is a Python package for setting up, processing, and analyzing solid-state defect calculations with VASP.
  dev_url: https://github.com/SMTG-UCL/doped

extra:
  recipe-maintainers:
    - kavanase
